---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 11.6.0
  use_vagrant_berkshelf_plugin: true

platforms:
- name: ubuntu-12.04

suites:
- name: default
  run_list: ["recipe[new_relic]"]
  attributes: {}
- name: mysql_monitor
  run_list: ["recipe[new_relic::mysql_monitor]"]
  attributes: {}
