---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 11.6.0
  use_vagrant_berkshelf_plugin: true

platforms:
- name: ubuntu-12.04

suites:
- name: default
  run_list: ["recipe[new_relic]"]
  data_bag_path: test/integration/data_bags
  encrypted_data_bag_secret_key_path: test/integration/data_bags/encrypted_data_bag_secret
  attributes: {}
- name: mysql_monitor
  run_list: ["recipe[new_relic::mysql_monitor]"]
  data_bag_path: test/integration/data_bags
  encrypted_data_bag_secret_key_path: test/integration/data_bags/encrypted_data_bag_secret
  attributes: {}
